/home/natal/anaconda2/envs/py2.7/lib/python2.7/site-packages/matplotlib/font_manager.py:1331: UserWarning: findfont: Font family [u'Arial'] not found. Falling back to DejaVu Sans
  (prop.get_family(), self.defaultFamily[fontext]))
02-06 21:20:14 matplotlib.backends._backend_tk                         INFO     line:1060 new_figure_manager_given_figure Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
/home/natal/anaconda2/envs/py2.7/lib/python2.7/site-packages/matplotlib/font_manager.py:1331: UserWarning: findfont: Font family [u'Arial'] not found. Falling back to DejaVu Sans
  (prop.get_family(), self.defaultFamily[fontext]))
02-06 21:21:32 matplotlib.backends._backend_tk                         INFO     line:1060 new_figure_manager_given_figure Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
/home/natal/anaconda2/envs/py2.7/lib/python2.7/site-packages/matplotlib/font_manager.py:1331: UserWarning: findfont: Font family [u'Arial'] not found. Falling back to DejaVu Sans
  (prop.get_family(), self.defaultFamily[fontext]))
02-06 21:24:56 matplotlib.backends._backend_tk                         INFO     line:1060 new_figure_manager_given_figure Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
  File "/home/natal/Documents/datacloud/software/rhino/v3/dcrhino_lib/dcrhino3/acquisition/real_time_acquisition_v1.1.py", line 456
    if len(self.buffer) != 0:
     ^
IndentationError: expected an indented block
/home/natal/anaconda2/envs/py2.7/lib/python2.7/site-packages/matplotlib/font_manager.py:1331: UserWarning: findfont: Font family [u'Arial'] not found. Falling back to DejaVu Sans
  (prop.get_family(), self.defaultFamily[fontext]))
  File "/home/natal/Documents/datacloud/software/rhino/v3/dcrhino_lib/dcrhino3/acquisition/real_time_acquisition_v1.1.py", line 456
    if len(self.buffer) != 0:
     ^
IndentationError: expected an indented block
/home/natal/anaconda2/envs/py2.7/lib/python2.7/site-packages/matplotlib/font_manager.py:1331: UserWarning: findfont: Font family [u'Arial'] not found. Falling back to DejaVu Sans
  (prop.get_family(), self.defaultFamily[fontext]))
  File "/home/natal/Documents/datacloud/software/rhino/v3/dcrhino_lib/dcrhino3/acquisition/real_time_acquisition_v1.1.py", line 456
    if len(self.buffer) != 0:
     ^
IndentationError: expected an indented block
/home/natal/anaconda2/envs/py2.7/lib/python2.7/site-packages/matplotlib/font_manager.py:1331: UserWarning: findfont: Font family [u'Arial'] not found. Falling back to DejaVu Sans
  (prop.get_family(), self.defaultFamily[fontext]))
/home/natal/anaconda2/envs/py2.7/lib/python2.7/site-packages/matplotlib/font_manager.py:1331: UserWarning: findfont: Font family [u'Arial'] not found. Falling back to DejaVu Sans
  (prop.get_family(), self.defaultFamily[fontext]))
02-06 21:29:41 matplotlib.backends._backend_tk                         INFO     line:1060 new_figure_manager_given_figure Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
02-06 21:35:58 matplotlib.backends._backend_tk                         INFO     line:1060 new_figure_manager_given_figure Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
/home/natal/anaconda2/envs/py2.7/lib/python2.7/site-packages/matplotlib/font_manager.py:1331: UserWarning: findfont: Font family [u'Arial'] not found. Falling back to DejaVu Sans
  (prop.get_family(), self.defaultFamily[fontext]))
/home/natal/anaconda2/envs/py2.7/lib/python2.7/site-packages/matplotlib/font_manager.py:1331: UserWarning: findfont: Font family [u'Arial'] not found. Falling back to DejaVu Sans
  (prop.get_family(), self.defaultFamily[fontext]))
02-06 21:38:24 matplotlib.backends._backend_tk                         INFO     line:1060 new_figure_manager_given_figure Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
/home/natal/anaconda2/envs/py2.7/lib/python2.7/site-packages/matplotlib/font_manager.py:1331: UserWarning: findfont: Font family [u'Arial'] not found. Falling back to DejaVu Sans
  (prop.get_family(), self.defaultFamily[fontext]))
02-06 21:51:15 matplotlib.backends._backend_tk                         INFO     line:1060 new_figure_manager_given_figure Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
/home/natal/anaconda2/envs/py2.7/lib/python2.7/site-packages/matplotlib/font_manager.py:1331: UserWarning: findfont: Font family [u'Arial'] not found. Falling back to DejaVu Sans
  (prop.get_family(), self.defaultFamily[fontext]))
02-06 21:51:30 matplotlib.backends._backend_tk                         INFO     line:1060 new_figure_manager_given_figure Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
/home/natal/anaconda2/envs/py2.7/lib/python2.7/site-packages/scipy/signal/_arraytools.py:45: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  b = a[a_slice]
/home/natal/anaconda2/envs/py2.7/lib/python2.7/site-packages/scipy/signal/signaltools.py:1341: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  out_full[ind] += zi
/home/natal/anaconda2/envs/py2.7/lib/python2.7/site-packages/scipy/signal/signaltools.py:1344: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  out = out_full[ind]
/home/natal/anaconda2/envs/py2.7/lib/python2.7/site-packages/scipy/signal/signaltools.py:1350: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  zf = out_full[ind]
02-06 21:52:29 matplotlib.font_manager                         DEBUG    line:1346 findfont findfont: Matching :family=sans-serif:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0 to DejaVu Sans (u'/home/natal/anaconda2/lib/python2.7/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf') with score of 0.050000
02-06 21:52:29 matplotlib.font_manager                         DEBUG    line:1346 findfont findfont: Matching :family=sans-serif:style=normal:variant=normal:weight=normal:stretch=normal:size=12.0 to DejaVu Sans (u'/home/natal/anaconda2/lib/python2.7/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf') with score of 0.050000
/home/natal/anaconda2/envs/py2.7/lib/python2.7/site-packages/matplotlib/font_manager.py:1331: UserWarning: findfont: Font family [u'Arial'] not found. Falling back to DejaVu Sans
  (prop.get_family(), self.defaultFamily[fontext]))
02-06 21:54:50 matplotlib.backends._backend_tk                         INFO     line:1060 new_figure_manager_given_figure Could not load matplotlib icon: can't use "pyimage1" as iconphoto: not a photo image
/home/natal/anaconda2/envs/py2.7/lib/python2.7/site-packages/scipy/signal/_arraytools.py:45: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  b = a[a_slice]
/home/natal/anaconda2/envs/py2.7/lib/python2.7/site-packages/scipy/signal/signaltools.py:1341: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  out_full[ind] += zi
/home/natal/anaconda2/envs/py2.7/lib/python2.7/site-packages/scipy/signal/signaltools.py:1344: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  out = out_full[ind]
/home/natal/anaconda2/envs/py2.7/lib/python2.7/site-packages/scipy/signal/signaltools.py:1350: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  zf = out_full[ind]
02-06 21:54:52 matplotlib.font_manager                         DEBUG    line:1346 findfont findfont: Matching :family=sans-serif:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0 to DejaVu Sans (u'/home/natal/anaconda2/lib/python2.7/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf') with score of 0.050000
02-06 21:54:52 matplotlib.font_manager                         DEBUG    line:1346 findfont findfont: Matching :family=sans-serif:style=normal:variant=normal:weight=normal:stretch=normal:size=12.0 to DejaVu Sans (u'/home/natal/anaconda2/lib/python2.7/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf') with score of 0.050000
/home/natal/anaconda2/envs/py2.7/lib/python2.7/site-packages/matplotlib/font_manager.py:1331: UserWarning: findfont: Font family [u'Arial'] not found. Falling back to DejaVu Sans
  (prop.get_family(), self.defaultFamily[fontext]))
Traceback (most recent call last):
  File "/home/natal/Documents/datacloud/software/rhino/v3/dcrhino_lib/dcrhino3/acquisition/real_time_acquisition_v1.1.py", line 41, in <module>
    from dcrhino3.external.seismic_wiggle import seismic_wiggle
ImportError: No module named external.seismic_wiggle
/home/natal/anaconda2/envs/py2.7/lib/python2.7/site-packages/matplotlib/font_manager.py:1331: UserWarning: findfont: Font family [u'Arial'] not found. Falling back to DejaVu Sans
  (prop.get_family(), self.defaultFamily[fontext]))
Traceback (most recent call last):
  File "/home/natal/Documents/datacloud/software/rhino/v3/dcrhino_lib/dcrhino3/acquisition/real_time_acquisition_v1.1.py", line 41, in <module>
    from dcrhino3.external.seismic_wiggle import seismic_wiggle
ImportError: No module named external.seismic_wiggle
